chore: set up cicd

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,8 +19,42 @@ jobs:
         go-version: 1.21.5
 
     - name: Build 
-      run: go build -v .
+      run: |
+        go mod download
+        go build -v .
       env:
         PORT: ${{ secrets.PORT }}
         JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
+  
+  deploy:
+      runs-on: ubuntu-latest
+  
+      steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+  
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v1
+  
+      - name: Build and Push Docker Image
+        run: |
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          docker buildx create --use
+          docker buildx build -t yourusername/yourapp:latest -f .
+          docker push yourusername/yourapp:latest
+  
+      - name: SSH into EC2 Instance and Deploy
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          port: ${{ secrets.EC2_PORT }}
+  
+          script: |
+            sleep 10
+            docker pull yourusername/yourapp:latest
+            docker stop yourapp || true
+            docker rm yourapp || true
+            docker run -d -p 8080:8080 --name yourapp yourusername/yourapp:latest || (echo "Deployment failed" && exit 1)
 
